Add Jetpack Constants
Automattic/jetpack-beta pull request #72
Opened 2019-05-02 15:34 UTC by kraftbj

Add the constants settings page here instead of the JN companion plugin.

Right now, when asking folks to test things like beta blocks, there is no built-in way for beta testers to do this without manually adjusting config files.

2021-01-13 07:39 UTC, jeherve requested changes
I like that idea!

Maybe that content should be found under Jetpack > Beta though?

2021-01-13 07:39 UTC, jeherve commented on jetpack-beta.php
> +		}
You seem to be missing some content here.

```suggestion
		}
	}

	/**
```

2021-01-19 22:16 UTC, kraftbj commented
Going to port this over to the monorepo FYI.

2021-01-25 20:59 UTC, kraftbj commented
Closed in favor of https://github.com/Automattic/jetpack/pull/18537

2021-01-25 20:59 UTC, closed without merging